### PR TITLE
Next step in promise to be in thenable

### PR DESCRIPTION
**Pull request by fadzlan**

### CODE REVIEW

**Comment by k4ml** [comment]
Hmm, is there a real example on this ? I guess this only needed if `res` is not a global variable like in this example.

**Comment by k4ml** [comment]
I'm thinking maybe we can expand this into 2 examples, one that simply use a global variable, the other example without using global variable.

**Comment by fadzlan** [comment]
Its not because of the scope of the variable.The code runs three cycle on the event loop.

The first run just define the function inside the "then" function. The second run runs the promise and subsequently runs the "then" function.

The console.log will run during the first cycle, before the "then" runs, hence it will not get the values that is needed.

**Comment by k4ml** [comment]
Aah, that interesting. Something I need to learn more on promise. Thanks !.

**Pull request merged**
